micronaut:
  application:
    name: keyManagerRest

grpc:
  client:
    plaintext: true
    max-retry-attempts: 10
  channels:
    keyManagerGrpc:
      address: ${KEY_MANAGER_GRPC_URI:`localhost:50051`}